(1-3)中級 Eメール重複チェック
hayabusa23/ex-emp-management-bugfix pull request #14
Opened 2024-06-07 05:29 UTC by Mochi-frontend

2024-06-07 05:29 UTC, Mochi-frontend commented
a

2024-06-07 07:05 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-07 07:05 UTC, igamasayuki commented on src/main/java/com/example/service/AdministratorService.java
> +		} else {
Serviceはメールアドレス存在チェックだけ行い、trueかfalseを返すのみにしてください。

そして、エラーメッセージの登録はControllerで行ってください。

2024-06-07 07:05 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		}
このif文は不要です。
管理者登録をした後に再度入力値チェックをしています。

2024-06-10 04:49 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-10 04:49 UTC, merged